apiVersion: v1
kind: Service
metadata:
  name: monappli
spec:
  ports:
    - nodePort: 31280
      port: 8080
      protocol: TCP
      targetPort: 5000
  selector:
    app: monappli
  type: NodePort
  